### PR TITLE
fix pending nodes not properly clearing and remove redundant function

### PR DESCRIPTION
**Pull request by ducch**

### CODE REVIEW

**Comment by mgp25** [comment]
@ducch `pending_nodes` is a protected variable from `whatsprot.class.php` that why we need a get for `IqHandler.php`

Regards

**Comment by ducch** [comment]
IqHandler is an inherited class of WhatsProt and can access protected variables of WhatsProt.
You cannot unset(getPendingNodes()[offset)). getPendingNodes() only returns the value of $whatsprot->pending_nodes.
This unset() doesn't affect the actual pending_nodes. Because of this, the pending_nodes list is only increasing and stuff is being re-sent over and over again.

**Comment by mgp25** [comment]
@ducch but i `IqHandler.php` doesnt extends `WhatsProt`

**Comment by ducch** [comment]
Not only it has access to protected variables, it also has access to private ones. It makes use of the actual WhatsProt instance.
See the construction [here](https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L2314) using `$handler = new IqHandler($this, $node);`.
It then defines IqHandler->parent as the WhatsProt instance, see [here](https://github.com/WHAnonymous/Chat-API/blob/master/src/handlers/IqHandler.php#L22).
Therefore, IqHandler->parent->pending_nodes has access to everything. There's no need for that function. Not only there's no need for it, you cannot even unset() (or add) anything using that function as it is.

**Comment by sinjuice** [comment]
Even if the parent is the actual instance of whatsprot, it's private/protected functions are inaccesible as any other instance of any class. Protected functions and variables are accesible only by extending. 

Look at the example, you will get a fatal error, cannot access protected property. 

[test_protected.txt](https://github.com/WHAnonymous/Chat-API/files/87117/test_protected.txt)


In other hand you are right about the unset not doing what is supposed to do, and in that case there are two solutions, setting pending_nodes as public or what is preferable add a removePendingNode function in the parent.

**Pull request closed without merging**
