### PR TITLE
Fixed typo with `readInt31` and unpacking `readInt20` value.

### PR DESCRIPTION
**Pull request by viniciusjarina**
Fetching pictures was not working due the wrong `peekInt20` calculation.

### CODE REVIEW

**Comment by mgp25** [comment]
@viniciusjarina profile pictures you mean right?

**Comment by viniciusjarina** [comment]
Yes :wink: 

Profile pictures..

**Comment by viniciusjarina** [comment]
Perhaps this will fix https://github.com/WHAnonymous/Chat-API/issues/1351

**Comment by breakerh** [comment]
I will check it now

**Comment by breakerh** [comment]
Looks like this fixes the profile pictures.. 
And also fixed the normal pictures that are send!

But you wil have to catch the images reading the node. If you use the bind function/event handlers you won't get the correct data (and only the thumbnail works)

**Pull request merged**
